// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.11.4
// source: github.com/google/xtoproto/proto/wirepath/wirepath.proto

package wirepath

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type WirePath_SpecialPath int32

const (
	WirePath_SPECIAL_PATH_UNSPECIFIED WirePath_SpecialPath = 0
	WirePath_SELF                     WirePath_SpecialPath = 1
)

// Enum value maps for WirePath_SpecialPath.
var (
	WirePath_SpecialPath_name = map[int32]string{
		0: "SPECIAL_PATH_UNSPECIFIED",
		1: "SELF",
	}
	WirePath_SpecialPath_value = map[string]int32{
		"SPECIAL_PATH_UNSPECIFIED": 0,
		"SELF":                     1,
	}
)

func (x WirePath_SpecialPath) Enum() *WirePath_SpecialPath {
	p := new(WirePath_SpecialPath)
	*p = x
	return p
}

func (x WirePath_SpecialPath) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WirePath_SpecialPath) Descriptor() protoreflect.EnumDescriptor {
	return file_github_com_google_xtoproto_proto_wirepath_wirepath_proto_enumTypes[0].Descriptor()
}

func (WirePath_SpecialPath) Type() protoreflect.EnumType {
	return &file_github_com_google_xtoproto_proto_wirepath_wirepath_proto_enumTypes[0]
}

func (x WirePath_SpecialPath) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WirePath_SpecialPath.Descriptor instead.
func (WirePath_SpecialPath) EnumDescriptor() ([]byte, []int) {
	return file_github_com_google_xtoproto_proto_wirepath_wirepath_proto_rawDescGZIP(), []int{0, 0}
}

type WirePath struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Element:
	//	*WirePath_FieldNumber
	//	*WirePath_SpecialPath_
	Element   isWirePath_Element `protobuf_oneof:"element"`
	FieldName string             `protobuf:"bytes,2,opt,name=field_name,json=fieldName,proto3" json:"field_name,omitempty"`
	Child     *WirePath          `protobuf:"bytes,3,opt,name=child,proto3" json:"child,omitempty"`
	// Types that are assignable to Slot:
	//	*WirePath_RepeatedFieldOffset
	//	*WirePath_MapKeyString
	//	*WirePath_MapKeyInt32
	//	*WirePath_MapKeyInt64
	//	*WirePath_MapKeyUint32
	//	*WirePath_MapKeyUint64
	//	*WirePath_MapKeySint32
	//	*WirePath_MapKeySint64
	//	*WirePath_MapKeyFixed32
	//	*WirePath_MapKeyFixed64
	//	*WirePath_MapKeySfixed32
	//	*WirePath_MapKeySfixed64
	//	*WirePath_MapKeyBool
	Slot isWirePath_Slot `protobuf_oneof:"slot"`
}

func (x *WirePath) Reset() {
	*x = WirePath{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_google_xtoproto_proto_wirepath_wirepath_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WirePath) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WirePath) ProtoMessage() {}

func (x *WirePath) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_google_xtoproto_proto_wirepath_wirepath_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WirePath.ProtoReflect.Descriptor instead.
func (*WirePath) Descriptor() ([]byte, []int) {
	return file_github_com_google_xtoproto_proto_wirepath_wirepath_proto_rawDescGZIP(), []int{0}
}

func (m *WirePath) GetElement() isWirePath_Element {
	if m != nil {
		return m.Element
	}
	return nil
}

func (x *WirePath) GetFieldNumber() int32 {
	if x, ok := x.GetElement().(*WirePath_FieldNumber); ok {
		return x.FieldNumber
	}
	return 0
}

func (x *WirePath) GetSpecialPath() WirePath_SpecialPath {
	if x, ok := x.GetElement().(*WirePath_SpecialPath_); ok {
		return x.SpecialPath
	}
	return WirePath_SPECIAL_PATH_UNSPECIFIED
}

func (x *WirePath) GetFieldName() string {
	if x != nil {
		return x.FieldName
	}
	return ""
}

func (x *WirePath) GetChild() *WirePath {
	if x != nil {
		return x.Child
	}
	return nil
}

func (m *WirePath) GetSlot() isWirePath_Slot {
	if m != nil {
		return m.Slot
	}
	return nil
}

func (x *WirePath) GetRepeatedFieldOffset() int64 {
	if x, ok := x.GetSlot().(*WirePath_RepeatedFieldOffset); ok {
		return x.RepeatedFieldOffset
	}
	return 0
}

func (x *WirePath) GetMapKeyString() string {
	if x, ok := x.GetSlot().(*WirePath_MapKeyString); ok {
		return x.MapKeyString
	}
	return ""
}

func (x *WirePath) GetMapKeyInt32() int32 {
	if x, ok := x.GetSlot().(*WirePath_MapKeyInt32); ok {
		return x.MapKeyInt32
	}
	return 0
}

func (x *WirePath) GetMapKeyInt64() int64 {
	if x, ok := x.GetSlot().(*WirePath_MapKeyInt64); ok {
		return x.MapKeyInt64
	}
	return 0
}

func (x *WirePath) GetMapKeyUint32() uint32 {
	if x, ok := x.GetSlot().(*WirePath_MapKeyUint32); ok {
		return x.MapKeyUint32
	}
	return 0
}

func (x *WirePath) GetMapKeyUint64() uint64 {
	if x, ok := x.GetSlot().(*WirePath_MapKeyUint64); ok {
		return x.MapKeyUint64
	}
	return 0
}

func (x *WirePath) GetMapKeySint32() int32 {
	if x, ok := x.GetSlot().(*WirePath_MapKeySint32); ok {
		return x.MapKeySint32
	}
	return 0
}

func (x *WirePath) GetMapKeySint64() int64 {
	if x, ok := x.GetSlot().(*WirePath_MapKeySint64); ok {
		return x.MapKeySint64
	}
	return 0
}

func (x *WirePath) GetMapKeyFixed32() uint32 {
	if x, ok := x.GetSlot().(*WirePath_MapKeyFixed32); ok {
		return x.MapKeyFixed32
	}
	return 0
}

func (x *WirePath) GetMapKeyFixed64() uint64 {
	if x, ok := x.GetSlot().(*WirePath_MapKeyFixed64); ok {
		return x.MapKeyFixed64
	}
	return 0
}

func (x *WirePath) GetMapKeySfixed32() int32 {
	if x, ok := x.GetSlot().(*WirePath_MapKeySfixed32); ok {
		return x.MapKeySfixed32
	}
	return 0
}

func (x *WirePath) GetMapKeySfixed64() int64 {
	if x, ok := x.GetSlot().(*WirePath_MapKeySfixed64); ok {
		return x.MapKeySfixed64
	}
	return 0
}

func (x *WirePath) GetMapKeyBool() bool {
	if x, ok := x.GetSlot().(*WirePath_MapKeyBool); ok {
		return x.MapKeyBool
	}
	return false
}

type isWirePath_Element interface {
	isWirePath_Element()
}

type WirePath_FieldNumber struct {
	FieldNumber int32 `protobuf:"varint,1,opt,name=field_number,json=fieldNumber,proto3,oneof"`
}

type WirePath_SpecialPath_ struct {
	SpecialPath WirePath_SpecialPath `protobuf:"varint,20,opt,name=special_path,json=specialPath,proto3,enum=xtoproto.wirepath.WirePath_SpecialPath,oneof"`
}

func (*WirePath_FieldNumber) isWirePath_Element() {}

func (*WirePath_SpecialPath_) isWirePath_Element() {}

type isWirePath_Slot interface {
	isWirePath_Slot()
}

type WirePath_RepeatedFieldOffset struct {
	RepeatedFieldOffset int64 `protobuf:"varint,4,opt,name=repeated_field_offset,json=repeatedFieldOffset,proto3,oneof"`
}

type WirePath_MapKeyString struct {
	MapKeyString string `protobuf:"bytes,5,opt,name=map_key_string,json=mapKeyString,proto3,oneof"`
}

type WirePath_MapKeyInt32 struct {
	MapKeyInt32 int32 `protobuf:"varint,6,opt,name=map_key_int32,json=mapKeyInt32,proto3,oneof"`
}

type WirePath_MapKeyInt64 struct {
	MapKeyInt64 int64 `protobuf:"varint,7,opt,name=map_key_int64,json=mapKeyInt64,proto3,oneof"`
}

type WirePath_MapKeyUint32 struct {
	MapKeyUint32 uint32 `protobuf:"varint,8,opt,name=map_key_uint32,json=mapKeyUint32,proto3,oneof"`
}

type WirePath_MapKeyUint64 struct {
	MapKeyUint64 uint64 `protobuf:"varint,9,opt,name=map_key_uint64,json=mapKeyUint64,proto3,oneof"`
}

type WirePath_MapKeySint32 struct {
	MapKeySint32 int32 `protobuf:"zigzag32,10,opt,name=map_key_sint32,json=mapKeySint32,proto3,oneof"`
}

type WirePath_MapKeySint64 struct {
	MapKeySint64 int64 `protobuf:"zigzag64,11,opt,name=map_key_sint64,json=mapKeySint64,proto3,oneof"`
}

type WirePath_MapKeyFixed32 struct {
	MapKeyFixed32 uint32 `protobuf:"fixed32,12,opt,name=map_key_fixed32,json=mapKeyFixed32,proto3,oneof"`
}

type WirePath_MapKeyFixed64 struct {
	MapKeyFixed64 uint64 `protobuf:"fixed64,13,opt,name=map_key_fixed64,json=mapKeyFixed64,proto3,oneof"`
}

type WirePath_MapKeySfixed32 struct {
	MapKeySfixed32 int32 `protobuf:"fixed32,14,opt,name=map_key_sfixed32,json=mapKeySfixed32,proto3,oneof"`
}

type WirePath_MapKeySfixed64 struct {
	MapKeySfixed64 int64 `protobuf:"fixed64,15,opt,name=map_key_sfixed64,json=mapKeySfixed64,proto3,oneof"`
}

type WirePath_MapKeyBool struct {
	MapKeyBool bool `protobuf:"varint,16,opt,name=map_key_bool,json=mapKeyBool,proto3,oneof"`
}

func (*WirePath_RepeatedFieldOffset) isWirePath_Slot() {}

func (*WirePath_MapKeyString) isWirePath_Slot() {}

func (*WirePath_MapKeyInt32) isWirePath_Slot() {}

func (*WirePath_MapKeyInt64) isWirePath_Slot() {}

func (*WirePath_MapKeyUint32) isWirePath_Slot() {}

func (*WirePath_MapKeyUint64) isWirePath_Slot() {}

func (*WirePath_MapKeySint32) isWirePath_Slot() {}

func (*WirePath_MapKeySint64) isWirePath_Slot() {}

func (*WirePath_MapKeyFixed32) isWirePath_Slot() {}

func (*WirePath_MapKeyFixed64) isWirePath_Slot() {}

func (*WirePath_MapKeySfixed32) isWirePath_Slot() {}

func (*WirePath_MapKeySfixed64) isWirePath_Slot() {}

func (*WirePath_MapKeyBool) isWirePath_Slot() {}

var File_github_com_google_xtoproto_proto_wirepath_wirepath_proto protoreflect.FileDescriptor

var file_github_com_google_xtoproto_proto_wirepath_wirepath_proto_rawDesc = []byte{
	0x0a, 0x38, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x78, 0x74, 0x6f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x77, 0x69, 0x72, 0x65, 0x70, 0x61, 0x74, 0x68, 0x2f, 0x77, 0x69, 0x72, 0x65,
	0x70, 0x61, 0x74, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x78, 0x74, 0x6f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x77, 0x69, 0x72, 0x65, 0x70, 0x61, 0x74, 0x68, 0x22, 0xb3, 0x06,
	0x0a, 0x08, 0x57, 0x69, 0x72, 0x65, 0x50, 0x61, 0x74, 0x68, 0x12, 0x23, 0x0a, 0x0c, 0x66, 0x69,
	0x65, 0x6c, 0x64, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x48, 0x00, 0x52, 0x0b, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12,
	0x4c, 0x0a, 0x0c, 0x73, 0x70, 0x65, 0x63, 0x69, 0x61, 0x6c, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18,
	0x14, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x27, 0x2e, 0x78, 0x74, 0x6f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x77, 0x69, 0x72, 0x65, 0x70, 0x61, 0x74, 0x68, 0x2e, 0x57, 0x69, 0x72, 0x65, 0x50, 0x61,
	0x74, 0x68, 0x2e, 0x53, 0x70, 0x65, 0x63, 0x69, 0x61, 0x6c, 0x50, 0x61, 0x74, 0x68, 0x48, 0x00,
	0x52, 0x0b, 0x73, 0x70, 0x65, 0x63, 0x69, 0x61, 0x6c, 0x50, 0x61, 0x74, 0x68, 0x12, 0x1d, 0x0a,
	0x0a, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x31, 0x0a, 0x05,
	0x63, 0x68, 0x69, 0x6c, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x78, 0x74,
	0x6f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x77, 0x69, 0x72, 0x65, 0x70, 0x61, 0x74, 0x68, 0x2e,
	0x57, 0x69, 0x72, 0x65, 0x50, 0x61, 0x74, 0x68, 0x52, 0x05, 0x63, 0x68, 0x69, 0x6c, 0x64, 0x12,
	0x34, 0x0a, 0x15, 0x72, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x66, 0x69, 0x65, 0x6c,
	0x64, 0x5f, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x48, 0x01,
	0x52, 0x13, 0x72, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4f,
	0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x26, 0x0a, 0x0e, 0x6d, 0x61, 0x70, 0x5f, 0x6b, 0x65, 0x79,
	0x5f, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52,
	0x0c, 0x6d, 0x61, 0x70, 0x4b, 0x65, 0x79, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x24, 0x0a,
	0x0d, 0x6d, 0x61, 0x70, 0x5f, 0x6b, 0x65, 0x79, 0x5f, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x05, 0x48, 0x01, 0x52, 0x0b, 0x6d, 0x61, 0x70, 0x4b, 0x65, 0x79, 0x49, 0x6e,
	0x74, 0x33, 0x32, 0x12, 0x24, 0x0a, 0x0d, 0x6d, 0x61, 0x70, 0x5f, 0x6b, 0x65, 0x79, 0x5f, 0x69,
	0x6e, 0x74, 0x36, 0x34, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x48, 0x01, 0x52, 0x0b, 0x6d, 0x61,
	0x70, 0x4b, 0x65, 0x79, 0x49, 0x6e, 0x74, 0x36, 0x34, 0x12, 0x26, 0x0a, 0x0e, 0x6d, 0x61, 0x70,
	0x5f, 0x6b, 0x65, 0x79, 0x5f, 0x75, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x0d, 0x48, 0x01, 0x52, 0x0c, 0x6d, 0x61, 0x70, 0x4b, 0x65, 0x79, 0x55, 0x69, 0x6e, 0x74, 0x33,
	0x32, 0x12, 0x26, 0x0a, 0x0e, 0x6d, 0x61, 0x70, 0x5f, 0x6b, 0x65, 0x79, 0x5f, 0x75, 0x69, 0x6e,
	0x74, 0x36, 0x34, 0x18, 0x09, 0x20, 0x01, 0x28, 0x04, 0x48, 0x01, 0x52, 0x0c, 0x6d, 0x61, 0x70,
	0x4b, 0x65, 0x79, 0x55, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x12, 0x26, 0x0a, 0x0e, 0x6d, 0x61, 0x70,
	0x5f, 0x6b, 0x65, 0x79, 0x5f, 0x73, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x11, 0x48, 0x01, 0x52, 0x0c, 0x6d, 0x61, 0x70, 0x4b, 0x65, 0x79, 0x53, 0x69, 0x6e, 0x74, 0x33,
	0x32, 0x12, 0x26, 0x0a, 0x0e, 0x6d, 0x61, 0x70, 0x5f, 0x6b, 0x65, 0x79, 0x5f, 0x73, 0x69, 0x6e,
	0x74, 0x36, 0x34, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x12, 0x48, 0x01, 0x52, 0x0c, 0x6d, 0x61, 0x70,
	0x4b, 0x65, 0x79, 0x53, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x12, 0x28, 0x0a, 0x0f, 0x6d, 0x61, 0x70,
	0x5f, 0x6b, 0x65, 0x79, 0x5f, 0x66, 0x69, 0x78, 0x65, 0x64, 0x33, 0x32, 0x18, 0x0c, 0x20, 0x01,
	0x28, 0x07, 0x48, 0x01, 0x52, 0x0d, 0x6d, 0x61, 0x70, 0x4b, 0x65, 0x79, 0x46, 0x69, 0x78, 0x65,
	0x64, 0x33, 0x32, 0x12, 0x28, 0x0a, 0x0f, 0x6d, 0x61, 0x70, 0x5f, 0x6b, 0x65, 0x79, 0x5f, 0x66,
	0x69, 0x78, 0x65, 0x64, 0x36, 0x34, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x06, 0x48, 0x01, 0x52, 0x0d,
	0x6d, 0x61, 0x70, 0x4b, 0x65, 0x79, 0x46, 0x69, 0x78, 0x65, 0x64, 0x36, 0x34, 0x12, 0x2a, 0x0a,
	0x10, 0x6d, 0x61, 0x70, 0x5f, 0x6b, 0x65, 0x79, 0x5f, 0x73, 0x66, 0x69, 0x78, 0x65, 0x64, 0x33,
	0x32, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x0f, 0x48, 0x01, 0x52, 0x0e, 0x6d, 0x61, 0x70, 0x4b, 0x65,
	0x79, 0x53, 0x66, 0x69, 0x78, 0x65, 0x64, 0x33, 0x32, 0x12, 0x2a, 0x0a, 0x10, 0x6d, 0x61, 0x70,
	0x5f, 0x6b, 0x65, 0x79, 0x5f, 0x73, 0x66, 0x69, 0x78, 0x65, 0x64, 0x36, 0x34, 0x18, 0x0f, 0x20,
	0x01, 0x28, 0x10, 0x48, 0x01, 0x52, 0x0e, 0x6d, 0x61, 0x70, 0x4b, 0x65, 0x79, 0x53, 0x66, 0x69,
	0x78, 0x65, 0x64, 0x36, 0x34, 0x12, 0x22, 0x0a, 0x0c, 0x6d, 0x61, 0x70, 0x5f, 0x6b, 0x65, 0x79,
	0x5f, 0x62, 0x6f, 0x6f, 0x6c, 0x18, 0x10, 0x20, 0x01, 0x28, 0x08, 0x48, 0x01, 0x52, 0x0a, 0x6d,
	0x61, 0x70, 0x4b, 0x65, 0x79, 0x42, 0x6f, 0x6f, 0x6c, 0x22, 0x35, 0x0a, 0x0b, 0x53, 0x70, 0x65,
	0x63, 0x69, 0x61, 0x6c, 0x50, 0x61, 0x74, 0x68, 0x12, 0x1c, 0x0a, 0x18, 0x53, 0x50, 0x45, 0x43,
	0x49, 0x41, 0x4c, 0x5f, 0x50, 0x41, 0x54, 0x48, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49,
	0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x53, 0x45, 0x4c, 0x46, 0x10, 0x01,
	0x42, 0x09, 0x0a, 0x07, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x42, 0x06, 0x0a, 0x04, 0x73,
	0x6c, 0x6f, 0x74, 0x42, 0x2b, 0x5a, 0x29, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x78, 0x74, 0x6f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x77, 0x69, 0x72, 0x65, 0x70, 0x61, 0x74, 0x68,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_github_com_google_xtoproto_proto_wirepath_wirepath_proto_rawDescOnce sync.Once
	file_github_com_google_xtoproto_proto_wirepath_wirepath_proto_rawDescData = file_github_com_google_xtoproto_proto_wirepath_wirepath_proto_rawDesc
)

func file_github_com_google_xtoproto_proto_wirepath_wirepath_proto_rawDescGZIP() []byte {
	file_github_com_google_xtoproto_proto_wirepath_wirepath_proto_rawDescOnce.Do(func() {
		file_github_com_google_xtoproto_proto_wirepath_wirepath_proto_rawDescData = protoimpl.X.CompressGZIP(file_github_com_google_xtoproto_proto_wirepath_wirepath_proto_rawDescData)
	})
	return file_github_com_google_xtoproto_proto_wirepath_wirepath_proto_rawDescData
}

var file_github_com_google_xtoproto_proto_wirepath_wirepath_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_github_com_google_xtoproto_proto_wirepath_wirepath_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_github_com_google_xtoproto_proto_wirepath_wirepath_proto_goTypes = []interface{}{
	(WirePath_SpecialPath)(0), // 0: xtoproto.wirepath.WirePath.SpecialPath
	(*WirePath)(nil),          // 1: xtoproto.wirepath.WirePath
}
var file_github_com_google_xtoproto_proto_wirepath_wirepath_proto_depIdxs = []int32{
	0, // 0: xtoproto.wirepath.WirePath.special_path:type_name -> xtoproto.wirepath.WirePath.SpecialPath
	1, // 1: xtoproto.wirepath.WirePath.child:type_name -> xtoproto.wirepath.WirePath
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_github_com_google_xtoproto_proto_wirepath_wirepath_proto_init() }
func file_github_com_google_xtoproto_proto_wirepath_wirepath_proto_init() {
	if File_github_com_google_xtoproto_proto_wirepath_wirepath_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_github_com_google_xtoproto_proto_wirepath_wirepath_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WirePath); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_github_com_google_xtoproto_proto_wirepath_wirepath_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*WirePath_FieldNumber)(nil),
		(*WirePath_SpecialPath_)(nil),
		(*WirePath_RepeatedFieldOffset)(nil),
		(*WirePath_MapKeyString)(nil),
		(*WirePath_MapKeyInt32)(nil),
		(*WirePath_MapKeyInt64)(nil),
		(*WirePath_MapKeyUint32)(nil),
		(*WirePath_MapKeyUint64)(nil),
		(*WirePath_MapKeySint32)(nil),
		(*WirePath_MapKeySint64)(nil),
		(*WirePath_MapKeyFixed32)(nil),
		(*WirePath_MapKeyFixed64)(nil),
		(*WirePath_MapKeySfixed32)(nil),
		(*WirePath_MapKeySfixed64)(nil),
		(*WirePath_MapKeyBool)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_github_com_google_xtoproto_proto_wirepath_wirepath_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_google_xtoproto_proto_wirepath_wirepath_proto_goTypes,
		DependencyIndexes: file_github_com_google_xtoproto_proto_wirepath_wirepath_proto_depIdxs,
		EnumInfos:         file_github_com_google_xtoproto_proto_wirepath_wirepath_proto_enumTypes,
		MessageInfos:      file_github_com_google_xtoproto_proto_wirepath_wirepath_proto_msgTypes,
	}.Build()
	File_github_com_google_xtoproto_proto_wirepath_wirepath_proto = out.File
	file_github_com_google_xtoproto_proto_wirepath_wirepath_proto_rawDesc = nil
	file_github_com_google_xtoproto_proto_wirepath_wirepath_proto_goTypes = nil
	file_github_com_google_xtoproto_proto_wirepath_wirepath_proto_depIdxs = nil
}
