// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.15.6
// source: github.com/google/xtoproto/proto/expression/expression.proto

package expression

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Expression struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Value:
	//	*Expression_Double
	//	*Expression_Float
	//	*Expression_Int32
	//	*Expression_Int64
	//	*Expression_Uint32
	//	*Expression_Uint64
	//	*Expression_Sint32
	//	*Expression_Sint64
	//	*Expression_Fixed32
	//	*Expression_Fixed64
	//	*Expression_Sfixed32
	//	*Expression_Sfixed64
	//	*Expression_Bool
	//	*Expression_String_
	//	*Expression_Bytes
	//	*Expression_Symbol
	//	*Expression_List
	//	*Expression_Other
	Value         isExpression_Value `protobuf_oneof:"value"`
	SourceContext *SourceContext     `protobuf:"bytes,21,opt,name=source_context,json=sourceContext,proto3" json:"source_context,omitempty"`
}

func (x *Expression) Reset() {
	*x = Expression{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_google_xtoproto_proto_expression_expression_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Expression) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Expression) ProtoMessage() {}

func (x *Expression) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_google_xtoproto_proto_expression_expression_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Expression.ProtoReflect.Descriptor instead.
func (*Expression) Descriptor() ([]byte, []int) {
	return file_github_com_google_xtoproto_proto_expression_expression_proto_rawDescGZIP(), []int{0}
}

func (m *Expression) GetValue() isExpression_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (x *Expression) GetDouble() float64 {
	if x, ok := x.GetValue().(*Expression_Double); ok {
		return x.Double
	}
	return 0
}

func (x *Expression) GetFloat() float32 {
	if x, ok := x.GetValue().(*Expression_Float); ok {
		return x.Float
	}
	return 0
}

func (x *Expression) GetInt32() int32 {
	if x, ok := x.GetValue().(*Expression_Int32); ok {
		return x.Int32
	}
	return 0
}

func (x *Expression) GetInt64() int64 {
	if x, ok := x.GetValue().(*Expression_Int64); ok {
		return x.Int64
	}
	return 0
}

func (x *Expression) GetUint32() uint32 {
	if x, ok := x.GetValue().(*Expression_Uint32); ok {
		return x.Uint32
	}
	return 0
}

func (x *Expression) GetUint64() uint64 {
	if x, ok := x.GetValue().(*Expression_Uint64); ok {
		return x.Uint64
	}
	return 0
}

func (x *Expression) GetSint32() int32 {
	if x, ok := x.GetValue().(*Expression_Sint32); ok {
		return x.Sint32
	}
	return 0
}

func (x *Expression) GetSint64() int64 {
	if x, ok := x.GetValue().(*Expression_Sint64); ok {
		return x.Sint64
	}
	return 0
}

func (x *Expression) GetFixed32() uint32 {
	if x, ok := x.GetValue().(*Expression_Fixed32); ok {
		return x.Fixed32
	}
	return 0
}

func (x *Expression) GetFixed64() uint64 {
	if x, ok := x.GetValue().(*Expression_Fixed64); ok {
		return x.Fixed64
	}
	return 0
}

func (x *Expression) GetSfixed32() int32 {
	if x, ok := x.GetValue().(*Expression_Sfixed32); ok {
		return x.Sfixed32
	}
	return 0
}

func (x *Expression) GetSfixed64() int64 {
	if x, ok := x.GetValue().(*Expression_Sfixed64); ok {
		return x.Sfixed64
	}
	return 0
}

func (x *Expression) GetBool() bool {
	if x, ok := x.GetValue().(*Expression_Bool); ok {
		return x.Bool
	}
	return false
}

func (x *Expression) GetString_() string {
	if x, ok := x.GetValue().(*Expression_String_); ok {
		return x.String_
	}
	return ""
}

func (x *Expression) GetBytes() []byte {
	if x, ok := x.GetValue().(*Expression_Bytes); ok {
		return x.Bytes
	}
	return nil
}

func (x *Expression) GetSymbol() *Symbol {
	if x, ok := x.GetValue().(*Expression_Symbol); ok {
		return x.Symbol
	}
	return nil
}

func (x *Expression) GetList() *List {
	if x, ok := x.GetValue().(*Expression_List); ok {
		return x.List
	}
	return nil
}

func (x *Expression) GetOther() *anypb.Any {
	if x, ok := x.GetValue().(*Expression_Other); ok {
		return x.Other
	}
	return nil
}

func (x *Expression) GetSourceContext() *SourceContext {
	if x != nil {
		return x.SourceContext
	}
	return nil
}

type isExpression_Value interface {
	isExpression_Value()
}

type Expression_Double struct {
	Double float64 `protobuf:"fixed64,1,opt,name=double,proto3,oneof"`
}

type Expression_Float struct {
	Float float32 `protobuf:"fixed32,2,opt,name=float,proto3,oneof"`
}

type Expression_Int32 struct {
	Int32 int32 `protobuf:"varint,3,opt,name=int32,proto3,oneof"`
}

type Expression_Int64 struct {
	Int64 int64 `protobuf:"varint,4,opt,name=int64,proto3,oneof"`
}

type Expression_Uint32 struct {
	Uint32 uint32 `protobuf:"varint,5,opt,name=uint32,proto3,oneof"`
}

type Expression_Uint64 struct {
	Uint64 uint64 `protobuf:"varint,6,opt,name=uint64,proto3,oneof"`
}

type Expression_Sint32 struct {
	Sint32 int32 `protobuf:"zigzag32,7,opt,name=sint32,proto3,oneof"`
}

type Expression_Sint64 struct {
	Sint64 int64 `protobuf:"zigzag64,8,opt,name=sint64,proto3,oneof"`
}

type Expression_Fixed32 struct {
	Fixed32 uint32 `protobuf:"fixed32,9,opt,name=fixed32,proto3,oneof"`
}

type Expression_Fixed64 struct {
	Fixed64 uint64 `protobuf:"fixed64,10,opt,name=fixed64,proto3,oneof"`
}

type Expression_Sfixed32 struct {
	Sfixed32 int32 `protobuf:"fixed32,11,opt,name=sfixed32,proto3,oneof"`
}

type Expression_Sfixed64 struct {
	Sfixed64 int64 `protobuf:"fixed64,12,opt,name=sfixed64,proto3,oneof"`
}

type Expression_Bool struct {
	Bool bool `protobuf:"varint,13,opt,name=bool,proto3,oneof"`
}

type Expression_String_ struct {
	String_ string `protobuf:"bytes,14,opt,name=string,proto3,oneof"`
}

type Expression_Bytes struct {
	Bytes []byte `protobuf:"bytes,15,opt,name=bytes,proto3,oneof"`
}

type Expression_Symbol struct {
	Symbol *Symbol `protobuf:"bytes,16,opt,name=symbol,proto3,oneof"`
}

type Expression_List struct {
	List *List `protobuf:"bytes,17,opt,name=list,proto3,oneof"`
}

type Expression_Other struct {
	Other *anypb.Any `protobuf:"bytes,20,opt,name=other,proto3,oneof"`
}

func (*Expression_Double) isExpression_Value() {}

func (*Expression_Float) isExpression_Value() {}

func (*Expression_Int32) isExpression_Value() {}

func (*Expression_Int64) isExpression_Value() {}

func (*Expression_Uint32) isExpression_Value() {}

func (*Expression_Uint64) isExpression_Value() {}

func (*Expression_Sint32) isExpression_Value() {}

func (*Expression_Sint64) isExpression_Value() {}

func (*Expression_Fixed32) isExpression_Value() {}

func (*Expression_Fixed64) isExpression_Value() {}

func (*Expression_Sfixed32) isExpression_Value() {}

func (*Expression_Sfixed64) isExpression_Value() {}

func (*Expression_Bool) isExpression_Value() {}

func (*Expression_String_) isExpression_Value() {}

func (*Expression_Bytes) isExpression_Value() {}

func (*Expression_Symbol) isExpression_Value() {}

func (*Expression_List) isExpression_Value() {}

func (*Expression_Other) isExpression_Value() {}

type List struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Elements []*Expression `protobuf:"bytes,1,rep,name=elements,proto3" json:"elements,omitempty"`
}

func (x *List) Reset() {
	*x = List{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_google_xtoproto_proto_expression_expression_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *List) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*List) ProtoMessage() {}

func (x *List) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_google_xtoproto_proto_expression_expression_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use List.ProtoReflect.Descriptor instead.
func (*List) Descriptor() ([]byte, []int) {
	return file_github_com_google_xtoproto_proto_expression_expression_proto_rawDescGZIP(), []int{1}
}

func (x *List) GetElements() []*Expression {
	if x != nil {
		return x.Elements
	}
	return nil
}

type SourceContext struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileName     string               `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	Range        *SourceContext_Range `protobuf:"bytes,2,opt,name=range,proto3" json:"range,omitempty"`
	DebugSummary string               `protobuf:"bytes,3,opt,name=debug_summary,json=debugSummary,proto3" json:"debug_summary,omitempty"`
	Details      []*anypb.Any         `protobuf:"bytes,4,rep,name=details,proto3" json:"details,omitempty"`
}

func (x *SourceContext) Reset() {
	*x = SourceContext{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_google_xtoproto_proto_expression_expression_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SourceContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceContext) ProtoMessage() {}

func (x *SourceContext) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_google_xtoproto_proto_expression_expression_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceContext.ProtoReflect.Descriptor instead.
func (*SourceContext) Descriptor() ([]byte, []int) {
	return file_github_com_google_xtoproto_proto_expression_expression_proto_rawDescGZIP(), []int{2}
}

func (x *SourceContext) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *SourceContext) GetRange() *SourceContext_Range {
	if x != nil {
		return x.Range
	}
	return nil
}

func (x *SourceContext) GetDebugSummary() string {
	if x != nil {
		return x.DebugSummary
	}
	return ""
}

func (x *SourceContext) GetDetails() []*anypb.Any {
	if x != nil {
		return x.Details
	}
	return nil
}

type Symbol struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
}

func (x *Symbol) Reset() {
	*x = Symbol{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_google_xtoproto_proto_expression_expression_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Symbol) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Symbol) ProtoMessage() {}

func (x *Symbol) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_google_xtoproto_proto_expression_expression_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Symbol.ProtoReflect.Descriptor instead.
func (*Symbol) Descriptor() ([]byte, []int) {
	return file_github_com_google_xtoproto_proto_expression_expression_proto_rawDescGZIP(), []int{3}
}

func (x *Symbol) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Symbol) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type SourceContext_CursorPosition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ByteOffset      *int64 `protobuf:"varint,1,opt,name=byte_offset,json=byteOffset,proto3,oneof" json:"byte_offset,omitempty"`
	Line            *int64 `protobuf:"varint,2,opt,name=line,proto3,oneof" json:"line,omitempty"`
	ColumnByte      *int64 `protobuf:"varint,3,opt,name=column_byte,json=columnByte,proto3,oneof" json:"column_byte,omitempty"`
	ColumnCharacter *int64 `protobuf:"varint,4,opt,name=column_character,json=columnCharacter,proto3,oneof" json:"column_character,omitempty"`
}

func (x *SourceContext_CursorPosition) Reset() {
	*x = SourceContext_CursorPosition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_google_xtoproto_proto_expression_expression_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SourceContext_CursorPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceContext_CursorPosition) ProtoMessage() {}

func (x *SourceContext_CursorPosition) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_google_xtoproto_proto_expression_expression_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceContext_CursorPosition.ProtoReflect.Descriptor instead.
func (*SourceContext_CursorPosition) Descriptor() ([]byte, []int) {
	return file_github_com_google_xtoproto_proto_expression_expression_proto_rawDescGZIP(), []int{2, 0}
}

func (x *SourceContext_CursorPosition) GetByteOffset() int64 {
	if x != nil && x.ByteOffset != nil {
		return *x.ByteOffset
	}
	return 0
}

func (x *SourceContext_CursorPosition) GetLine() int64 {
	if x != nil && x.Line != nil {
		return *x.Line
	}
	return 0
}

func (x *SourceContext_CursorPosition) GetColumnByte() int64 {
	if x != nil && x.ColumnByte != nil {
		return *x.ColumnByte
	}
	return 0
}

func (x *SourceContext_CursorPosition) GetColumnCharacter() int64 {
	if x != nil && x.ColumnCharacter != nil {
		return *x.ColumnCharacter
	}
	return 0
}

type SourceContext_Range struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Start *SourceContext_CursorPosition `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End   *SourceContext_CursorPosition `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
}

func (x *SourceContext_Range) Reset() {
	*x = SourceContext_Range{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_google_xtoproto_proto_expression_expression_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SourceContext_Range) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceContext_Range) ProtoMessage() {}

func (x *SourceContext_Range) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_google_xtoproto_proto_expression_expression_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceContext_Range.ProtoReflect.Descriptor instead.
func (*SourceContext_Range) Descriptor() ([]byte, []int) {
	return file_github_com_google_xtoproto_proto_expression_expression_proto_rawDescGZIP(), []int{2, 1}
}

func (x *SourceContext_Range) GetStart() *SourceContext_CursorPosition {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *SourceContext_Range) GetEnd() *SourceContext_CursorPosition {
	if x != nil {
		return x.End
	}
	return nil
}

var File_github_com_google_xtoproto_proto_expression_expression_proto protoreflect.FileDescriptor

var file_github_com_google_xtoproto_proto_expression_expression_proto_rawDesc = []byte{
	0x0a, 0x3c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x78, 0x74, 0x6f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x65, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2f, 0x65, 0x78,
	0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13,
	0x78, 0x74, 0x6f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x65, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xfc,
	0x04, 0x0a, 0x0a, 0x45, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a,
	0x06, 0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x48, 0x00, 0x52,
	0x06, 0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x05, 0x66, 0x6c, 0x6f, 0x61, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x48, 0x00, 0x52, 0x05, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x12,
	0x16, 0x0a, 0x05, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00,
	0x52, 0x05, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x12, 0x16, 0x0a, 0x05, 0x69, 0x6e, 0x74, 0x36, 0x34,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x48, 0x00, 0x52, 0x05, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x12,
	0x18, 0x0a, 0x06, 0x75, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x48,
	0x00, 0x52, 0x06, 0x75, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x12, 0x18, 0x0a, 0x06, 0x75, 0x69, 0x6e,
	0x74, 0x36, 0x34, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x48, 0x00, 0x52, 0x06, 0x75, 0x69, 0x6e,
	0x74, 0x36, 0x34, 0x12, 0x18, 0x0a, 0x06, 0x73, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x11, 0x48, 0x00, 0x52, 0x06, 0x73, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x12, 0x18, 0x0a,
	0x06, 0x73, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x18, 0x08, 0x20, 0x01, 0x28, 0x12, 0x48, 0x00, 0x52,
	0x06, 0x73, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x12, 0x1a, 0x0a, 0x07, 0x66, 0x69, 0x78, 0x65, 0x64,
	0x33, 0x32, 0x18, 0x09, 0x20, 0x01, 0x28, 0x07, 0x48, 0x00, 0x52, 0x07, 0x66, 0x69, 0x78, 0x65,
	0x64, 0x33, 0x32, 0x12, 0x1a, 0x0a, 0x07, 0x66, 0x69, 0x78, 0x65, 0x64, 0x36, 0x34, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x06, 0x48, 0x00, 0x52, 0x07, 0x66, 0x69, 0x78, 0x65, 0x64, 0x36, 0x34, 0x12,
	0x1c, 0x0a, 0x08, 0x73, 0x66, 0x69, 0x78, 0x65, 0x64, 0x33, 0x32, 0x18, 0x0b, 0x20, 0x01, 0x28,
	0x0f, 0x48, 0x00, 0x52, 0x08, 0x73, 0x66, 0x69, 0x78, 0x65, 0x64, 0x33, 0x32, 0x12, 0x1c, 0x0a,
	0x08, 0x73, 0x66, 0x69, 0x78, 0x65, 0x64, 0x36, 0x34, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x10, 0x48,
	0x00, 0x52, 0x08, 0x73, 0x66, 0x69, 0x78, 0x65, 0x64, 0x36, 0x34, 0x12, 0x14, 0x0a, 0x04, 0x62,
	0x6f, 0x6f, 0x6c, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x04, 0x62, 0x6f, 0x6f,
	0x6c, 0x12, 0x18, 0x0a, 0x06, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x0e, 0x20, 0x01, 0x28,
	0x09, 0x48, 0x00, 0x52, 0x06, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x16, 0x0a, 0x05, 0x62,
	0x79, 0x74, 0x65, 0x73, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x05, 0x62, 0x79,
	0x74, 0x65, 0x73, 0x12, 0x35, 0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x10, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x78, 0x74, 0x6f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x65,
	0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c,
	0x48, 0x00, 0x52, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x2f, 0x0a, 0x04, 0x6c, 0x69,
	0x73, 0x74, 0x18, 0x11, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x78, 0x74, 0x6f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x65, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x48, 0x00, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x05, 0x6f,
	0x74, 0x68, 0x65, 0x72, 0x18, 0x14, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79,
	0x48, 0x00, 0x52, 0x05, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x12, 0x49, 0x0a, 0x0e, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x18, 0x15, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x22, 0x2e, 0x78, 0x74, 0x6f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x65, 0x78, 0x70,
	0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x43, 0x6f,
	0x6e, 0x74, 0x65, 0x78, 0x74, 0x52, 0x0d, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x43, 0x6f, 0x6e,
	0x74, 0x65, 0x78, 0x74, 0x42, 0x07, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x43, 0x0a,
	0x04, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x3b, 0x0a, 0x08, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x78, 0x74, 0x6f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x65, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x45, 0x78,
	0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x73, 0x22, 0xbf, 0x04, 0x0a, 0x0d, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x43, 0x6f, 0x6e,
	0x74, 0x65, 0x78, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x3e, 0x0a, 0x05, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x28, 0x2e, 0x78, 0x74, 0x6f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x65, 0x78, 0x70, 0x72,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x43, 0x6f, 0x6e,
	0x74, 0x65, 0x78, 0x74, 0x2e, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x05, 0x72, 0x61, 0x6e, 0x67,
	0x65, 0x12, 0x23, 0x0a, 0x0d, 0x64, 0x65, 0x62, 0x75, 0x67, 0x5f, 0x73, 0x75, 0x6d, 0x6d, 0x61,
	0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x64, 0x65, 0x62, 0x75, 0x67, 0x53,
	0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x12, 0x2e, 0x0a, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x07, 0x64,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x1a, 0xe3, 0x01, 0x0a, 0x0e, 0x43, 0x75, 0x72, 0x73, 0x6f,
	0x72, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x24, 0x0a, 0x0b, 0x62, 0x79, 0x74,
	0x65, 0x5f, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x48, 0x00,
	0x52, 0x0a, 0x62, 0x79, 0x74, 0x65, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x88, 0x01, 0x01, 0x12,
	0x17, 0x0a, 0x04, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x48, 0x01, 0x52,
	0x04, 0x6c, 0x69, 0x6e, 0x65, 0x88, 0x01, 0x01, 0x12, 0x24, 0x0a, 0x0b, 0x63, 0x6f, 0x6c, 0x75,
	0x6d, 0x6e, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x48, 0x02, 0x52,
	0x0a, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x42, 0x79, 0x74, 0x65, 0x88, 0x01, 0x01, 0x12, 0x2e,
	0x0a, 0x10, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x5f, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74,
	0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x48, 0x03, 0x52, 0x0f, 0x63, 0x6f, 0x6c, 0x75,
	0x6d, 0x6e, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x88, 0x01, 0x01, 0x42, 0x0e,
	0x0a, 0x0c, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x5f, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x42, 0x07,
	0x0a, 0x05, 0x5f, 0x6c, 0x69, 0x6e, 0x65, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x63, 0x6f, 0x6c, 0x75,
	0x6d, 0x6e, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x42, 0x13, 0x0a, 0x11, 0x5f, 0x63, 0x6f, 0x6c, 0x75,
	0x6d, 0x6e, 0x5f, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x1a, 0x95, 0x01, 0x0a,
	0x05, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x47, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x31, 0x2e, 0x78, 0x74, 0x6f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x65, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x2e, 0x43, 0x75, 0x72, 0x73, 0x6f, 0x72,
	0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x12,
	0x43, 0x0a, 0x03, 0x65, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x31, 0x2e, 0x78,
	0x74, 0x6f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x65, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x2e, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74,
	0x2e, 0x43, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x03, 0x65, 0x6e, 0x64, 0x22, 0x3a, 0x0a, 0x06, 0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65,
	0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x78, 0x74, 0x6f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_github_com_google_xtoproto_proto_expression_expression_proto_rawDescOnce sync.Once
	file_github_com_google_xtoproto_proto_expression_expression_proto_rawDescData = file_github_com_google_xtoproto_proto_expression_expression_proto_rawDesc
)

func file_github_com_google_xtoproto_proto_expression_expression_proto_rawDescGZIP() []byte {
	file_github_com_google_xtoproto_proto_expression_expression_proto_rawDescOnce.Do(func() {
		file_github_com_google_xtoproto_proto_expression_expression_proto_rawDescData = protoimpl.X.CompressGZIP(file_github_com_google_xtoproto_proto_expression_expression_proto_rawDescData)
	})
	return file_github_com_google_xtoproto_proto_expression_expression_proto_rawDescData
}

var file_github_com_google_xtoproto_proto_expression_expression_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_github_com_google_xtoproto_proto_expression_expression_proto_goTypes = []interface{}{
	(*Expression)(nil),                   // 0: xtoproto.expression.Expression
	(*List)(nil),                         // 1: xtoproto.expression.List
	(*SourceContext)(nil),                // 2: xtoproto.expression.SourceContext
	(*Symbol)(nil),                       // 3: xtoproto.expression.Symbol
	(*SourceContext_CursorPosition)(nil), // 4: xtoproto.expression.SourceContext.CursorPosition
	(*SourceContext_Range)(nil),          // 5: xtoproto.expression.SourceContext.Range
	(*anypb.Any)(nil),                    // 6: google.protobuf.Any
}
var file_github_com_google_xtoproto_proto_expression_expression_proto_depIdxs = []int32{
	3, // 0: xtoproto.expression.Expression.symbol:type_name -> xtoproto.expression.Symbol
	1, // 1: xtoproto.expression.Expression.list:type_name -> xtoproto.expression.List
	6, // 2: xtoproto.expression.Expression.other:type_name -> google.protobuf.Any
	2, // 3: xtoproto.expression.Expression.source_context:type_name -> xtoproto.expression.SourceContext
	0, // 4: xtoproto.expression.List.elements:type_name -> xtoproto.expression.Expression
	5, // 5: xtoproto.expression.SourceContext.range:type_name -> xtoproto.expression.SourceContext.Range
	6, // 6: xtoproto.expression.SourceContext.details:type_name -> google.protobuf.Any
	4, // 7: xtoproto.expression.SourceContext.Range.start:type_name -> xtoproto.expression.SourceContext.CursorPosition
	4, // 8: xtoproto.expression.SourceContext.Range.end:type_name -> xtoproto.expression.SourceContext.CursorPosition
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_github_com_google_xtoproto_proto_expression_expression_proto_init() }
func file_github_com_google_xtoproto_proto_expression_expression_proto_init() {
	if File_github_com_google_xtoproto_proto_expression_expression_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_github_com_google_xtoproto_proto_expression_expression_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Expression); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_google_xtoproto_proto_expression_expression_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*List); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_google_xtoproto_proto_expression_expression_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SourceContext); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_google_xtoproto_proto_expression_expression_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Symbol); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_google_xtoproto_proto_expression_expression_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SourceContext_CursorPosition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_google_xtoproto_proto_expression_expression_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SourceContext_Range); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_github_com_google_xtoproto_proto_expression_expression_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Expression_Double)(nil),
		(*Expression_Float)(nil),
		(*Expression_Int32)(nil),
		(*Expression_Int64)(nil),
		(*Expression_Uint32)(nil),
		(*Expression_Uint64)(nil),
		(*Expression_Sint32)(nil),
		(*Expression_Sint64)(nil),
		(*Expression_Fixed32)(nil),
		(*Expression_Fixed64)(nil),
		(*Expression_Sfixed32)(nil),
		(*Expression_Sfixed64)(nil),
		(*Expression_Bool)(nil),
		(*Expression_String_)(nil),
		(*Expression_Bytes)(nil),
		(*Expression_Symbol)(nil),
		(*Expression_List)(nil),
		(*Expression_Other)(nil),
	}
	file_github_com_google_xtoproto_proto_expression_expression_proto_msgTypes[4].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_github_com_google_xtoproto_proto_expression_expression_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_google_xtoproto_proto_expression_expression_proto_goTypes,
		DependencyIndexes: file_github_com_google_xtoproto_proto_expression_expression_proto_depIdxs,
		MessageInfos:      file_github_com_google_xtoproto_proto_expression_expression_proto_msgTypes,
	}.Build()
	File_github_com_google_xtoproto_proto_expression_expression_proto = out.File
	file_github_com_google_xtoproto_proto_expression_expression_proto_rawDesc = nil
	file_github_com_google_xtoproto_proto_expression_expression_proto_goTypes = nil
	file_github_com_google_xtoproto_proto_expression_expression_proto_depIdxs = nil
}
